from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import httpx

from src.config import get_tasktracker_base_url, get_tasktracker_token


@dataclass
class TaskTrackerClient:
    """
    Minimal HTTP client for the TaskTracker API described in `api-docs.yaml`.

    This client focuses on the subset of operations needed for managing
    test cases:

    - Listing test cases in a folder.
    - Creating a new test case.
    - Updating an existing test case.
    - Deleting a test case.

    It can be extended as needed if you start using more of the OpenAPI spec.
    """

    base_url: str
    token: Optional[str] = None
    timeout: float = 30.0

    def __post_init__(self) -> None:
        self._client = httpx.Client(
            base_url=self.base_url,
            timeout=self.timeout,
            headers=self._build_headers(),
        )

    @classmethod
    def from_env(cls) -> "TaskTrackerClient":
        return cls(
            base_url=get_tasktracker_base_url(),
            token=get_tasktracker_token(),
        )

    def _build_headers(self) -> Dict[str, str]:
        headers: Dict[str, str] = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        return headers

    # --- Folder operations (TMS plugin) ---

    def get_root_folder_units(
        self,
        *,
        space_id_code: str = "TMS",
        page: int = 0,
        size: int = 50,
    ) -> Dict[str, Any]:
        """
        Get folder hierarchy from root and paginated units.

        POST /extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/root/units
        Request: getRootFolderRq (type TEST_CASE, spaceId), unitFilters (page).
        """
        body = {
            "getRootFolderRq": {
                "type": "TEST_CASE",
                "spaceId": {"code": space_id_code},
            },
            "linkedTo": None,
            "unitFilters": {"page": {"page": page, "size": size}},
        }
        response = self._client.post(
            "/extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/root/units",
            json=body,
        )
        response.raise_for_status()
        return response.json()

    def create_folder(
        self,
        name: str,
        parent_id_code: str,
        space_id_code: str = "TMS",
    ) -> Dict[str, Any]:
        """
        Create a folder under the given parent.

        POST /extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/create
        Request: name, parentId { code }, spaceId { code }.
        Response: FolderDto (id, key, title, children).
        """
        body = {
            "name": name,
            "parentId": {"code": parent_id_code},
            "spaceId": {"code": space_id_code},
        }
        response = self._client.post(
            "/extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/create",
            json=body,
        )
        response.raise_for_status()
        return response.json()

    # --- High-level operations used by tools ---

    def get_test_cases(
        self,
        folder_code: str,
        page: int = 0,
        size: int = 50,
    ) -> Dict[str, Any]:
        """
        Fetch test cases for a given folder.

        Uses the TMS plugin endpoint:
        `/extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/hierarchy/{folder_code}/units/filtered`
        with `type=TEST_CASE`.
        """
        body = {
            "type": "TEST_CASE",
            "linkedTo": None,
            "unitFilters": {
                "page": {"page": page, "size": size},
            },
        }
        response = self._client.post(
            f"/extension/plugin/v2/rest/api/swtr_tms_plugin/v1/folder/hierarchy/{folder_code}/units/filtered",
            json=body,
        )
        response.raise_for_status()
        return response.json()

    def create_test_case(
        self,
        suit: str,
        payload: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Create a new test case via:
        `/rest/api/unit/v2/{suit}/create`

        The exact schema for `payload` is defined by TaskTracker. You can
        pass through the JSON generated by the agent, as long as it matches
        what the server expects (for test cases that is typically `suit=test_case`).
        """
        response = self._client.post(
            f"/rest/api/unit/v2/{suit}/create",
            json=payload,
        )
        response.raise_for_status()
        return response.json()

    def get_test_case(self, code: str) -> Dict[str, Any]:
        """
        Fetch a single test case (unit) by code:
        `/rest/api/unit/v2/{code}`
        """
        response = self._client.get(f"/rest/api/unit/v2/{code}")
        response.raise_for_status()
        return response.json()

    def update_test_case(
        self,
        code: str,
        patch_body: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Update an existing test case:
        `/rest/api/unit/v2/update/{code}`
        """
        response = self._client.patch(
            f"/rest/api/unit/v2/update/{code}",
            json=patch_body,
        )
        response.raise_for_status()
        return response.json()

    def delete_test_case(self, code: str) -> Dict[str, Any]:
        """
        Best-effort delete for a test case.

        The OpenAPI spec exposes `204` for successful delete on the same
        `/rest/api/unit/v2/{suit}/create` operation; to avoid overfitting
        to that quirk, this method performs a PATCH with a workflow/status
        change or uses a dedicated delete endpoint if one is added later.

        For now, this is implemented as a no-op placeholder that should be
        adapted once a canonical delete operation is agreed on.
        """
        raise NotImplementedError(
            "delete_test_case is not wired to a concrete TaskTracker endpoint yet. "
            "Add the correct delete call when the API contract is finalized."
        )

    # --- Low-level helpers ---

    def close(self) -> None:
        self._client.close()


def flatten_test_cases(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Extract the list of test case units from the `FolderUnitsDto` response.
    """
    units_page = result.get("units") or {}
    content = units_page.get("content") or []
    return [item.get("unit", item) for item in content]

